image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

# Cache and keep downloaded dependencies between CI pipelines
cache:
  key: maven-build
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - cd code && mvn compile

test:
  stage: test
  script:
    - cd code && mvn test
